[package]
name = "migration-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
psl.workspace = true
introspection-connector = { path = "../../../introspection-engine/connectors/introspection-connector" }
user-facing-errors = { path = "../../../libs/user-facing-errors" }

chrono.workspace = true
enumflags2 = "0.7"
sha2 = "0.9.1"
tracing = "0.1"
tracing-error = "0.2"
